### ISSUE TITLE
Win32 Python Crashing on HybridEnc.decrypt()

### ISSUE THREAD

**Issue by tremor-sh** [nikosft/IB-PRE#2]
Hi, Thanks for the source. I am trying running your file pre_mg07a with the calling you provided in comments:

        from charm.toolbox.pairinggroup import PairingGroup,GT
	from charm.core.engine.util import objectToBytes,bytesToObject
	from charm.schemes.pkenc.pkenc_cs98 import CS98
	from charm.toolbox.ecgroup import ECGroup
	from charm.toolbox.eccurve import prime192v2
	group = PairingGroup('SS512', secparam=1024)
	groupcs98 = ECGroup(prime192v2)
	pkenc = CS98(groupcs98)
	pre = PreGA(group,pkenc)
	ID1 = "nikos fotiou"
	msg  =  group.random(GT)
	(master_secret_key, params) = pre.setup()
	(public_key, secret_key) = pkenc.keygen()
	id1_secret_key = pre.keyGen(master_secret_key, ID1)
	ciphertext = pre.encrypt(params, ID1, msg);
	re_encryption_key = pre.rkGenPKenc(params,id1_secret_key, public_key)
	ciphertext2 = pre.reEncryptPKenc(params, re_encryption_key, ciphertext)
	pre.decryptPKenc(params, public_key, secret_key, ciphertext2) #problem here

When the program reaches the last line, it crashes saying python.exe stopped working. I tried finding out the problem. It arises in when calling the decrypt function of hybridEnc
        Xbytes = pkenc.decrypt(public_key, secret_key, cid['C3'])

I am on MingW 32bit and python 3.4 on windows 7. I have installed all libraries: PBC 0.5.14, openssl 1.0.1, GMP 5.0.2, and charm 0.43
All other encryption and ciphertexts are being printed normally.

Questions:
Any idea about the problem? Any guidance?
What python version and charm versions were used?
What OS did you use? (im having python installation problems in ubuntu) 
When is the decrypt function of PreGA class to be used?

Thanks a lot.

**Comment by nikosft** [comment]
I am using Ubuntu 14.04. Currently I am away. I can check it in 10 days

**Comment by tremor-sh** [comment]
Oh, thanks so much for the reply. Alright, I understand. I'll be waiting

**Comment by nikosft** [comment]
Do you have access to any linux box? Can you try it there?

**Comment by tremor-sh** [comment]
Ok, I'll give it a try

**Comment by tremor-sh** [comment]
Just got it working on Ubuntu 14.04.

I used 12.04 previously which was a hassle. Here I faced problems configuring and making my previously download sources of PBC. Downloaded from scratch and it successfully configured. Also, couldn't make charm on python 2.7 work, then installed charm with python 3.4 which worked. Thanks a lot!
